// services/web/src/components/btn.tsx
import { Link } from "react-router-dom";

function render(props:any) {

    const defaultStyles = "text-white p-2 bg-homestyleblue rounded-lg inline-flex text-center justify-center"
    const usedSytles = props.extraStyles ? props.extraStyles : ""

    if(props.link) {
        return (<>
        <Link to={props.link} className={defaultStyles + " " + usedSytles}>{props.text}
            {props.children}
        </Link>
        </>)
    }

    return (<>
    <button className={defaultStyles + " " + usedSytles}>{props.text}
    {props.children}
    </button>
    </>)

}

export default render;

// services/web/components/btn.vue
<template>

  <nuxt-link v-if="link" :to="link" class="text-white p-2 bg-homestyleblue rounded-lg inline-flex text-center justify-center">
    {{text}}
  </nuxt-link>

  <button v-else>
    {{text}}
  </button>

</template>

<script setup lang="ts">

defineProps<{
  text?: string,
  link?: string,
}>()

</script>
