// services/web/components/menu/header.vue
<template>
  <div class="h-full bg-white p-5 flex md:hidden justify-between" @click.stop.prevent="">
    <Logo />
  <div class="flex items-center">
    <MagnifyingGlassIcon class="h-[30px] mr-3"/>
    <XMarkIcon class="h-[30px] cursor-pointer" @click="$emit('menuState')"/>
  </div>
  </div>
</template>

<script setup lang="ts">
 import {MagnifyingGlassIcon} from "@heroicons/vue/20/solid";
 import {XMarkIcon} from "@heroicons/vue/20/solid";

 function clickevent (e: Event): void {
   e.stopPropagation();

 }
</script>

// services/web/src/components/header/header.tsx
import Logo from "../logo";
import {MagnifyingGlassIcon, XMarkIcon} from "@heroicons/react/24/solid";

function render (props:any) {
    return (<>
        <div className="h-full bg-white p-5 flex md:hidden justify-between" onClick={(e) => { e.stopPropagation() }}>
            <Logo />
            <div className="flex items-center">
                <MagnifyingGlassIcon className="h-[30px] mr-3"/>
                <XMarkIcon className="h-[30px]" onClick={props.handleChange} />
            </div>
        </div>
    </>)
}


export default render
